services:
  nats:
    image: nats:latest
    container_name: nats
    command: -c /etc/nats/nats.conf
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - ./nats_data:/data/jetstream # <- mount for JetStream persistence
    ports:
      - "4222:4222" # NATS clients (apps/workers)
      - "8222:8222" # Monitoring UI (http://localhost:8222)
      - "1883:1883" # MQTT listener for ESP32
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Redis default port
    restart: unless-stopped

  aggregator:
    build: ./aggregator
    container_name: aggregator
    depends_on:
      - nats
      - redis
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - nats
    volumes:
      - ./api:/app
    restart: unless-stopped
